name: Update Portfolio Data

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements-data.txt

      - name: Run Script - Update Data
        run: python src/update_data.py

      - name: Debug Git Status
        run: |
          git status
          ls -lah data/
          cat data/portfolio.json || echo "File not found"

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "test: test workflow"
          git push origin master
