name: Update Site Contents

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: git pull origin master

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Run update_site Script
        run: python main.py --update-site

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Check for changes and commit if needed
        run: |
          git status
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "chore: update site content"
            git push origin master
          else
            echo "No changes to commit"
          fi
